services:
  - type: web
    name: weather-relatively
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
